# Generated by Django 4.2.29 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("poster", "Poster Design"),
                            ("social", "Social Media Posts"),
                            ("thumbnail", "YouTube Thumbnails"),
                            ("business_card", "Business Cards"),
                            ("wedding_card", "Wedding Cards"),
                            ("book_cover", "Book Covers"),
                        ],
                        max_length=30,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="services/")),
                ("badge_text", models.CharField(default="Design Service", max_length=40)),
                ("tier_text", models.CharField(default="Premium", max_length=40)),
                ("cta_text", models.CharField(default="Request this service", max_length=60)),
                ("is_published", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]

