# Generated by Django 4.2.29 on 2026-04-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='category',
            field=models.CharField(max_length=120),
        ),
    ]
