# Generated by Codex.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("poster", "Poster Design"),
                            ("social", "Social Media Posts"),
                            ("thumbnail", "YouTube Thumbnails"),
                            ("business_card", "Business Cards"),
                            ("wedding_card", "Wedding Cards"),
                            ("book_cover", "Book Covers"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="portfolio/"),
                ),
                ("client", models.CharField(blank=True, max_length=120)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
