# Generated by Django 4.2.29 on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("about_video", models.FileField(blank=True, null=True, upload_to="site/")),
                ("about_primary_image", models.ImageField(blank=True, null=True, upload_to="site/")),
                ("about_secondary_image", models.ImageField(blank=True, null=True, upload_to="site/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Content",
                "verbose_name_plural": "Site Content",
            },
        ),
    ]

