# Generated by Django 4.2.29 on 2026-03-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='payer_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='payment_mode',
            field=models.CharField(default='razorpay', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
